/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-04-23 15:01:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class addPet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Add Pet</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/paws.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body { background-color: #F6EFE7; }\r\n");
      out.write("        .card { max-width: 560px; margin: 36px auto; padding: 32px; border-radius: 20px; box-shadow: 0 20px 50px rgba(0,0,0,0.08); border: 1px solid rgba(140, 118, 92, 0.12); background-color: rgba(255,255,255,0.98); }\r\n");
      out.write("        .card h1 { text-align: center; color: #4a2c2a; margin-bottom: 24px; }\r\n");
      out.write("        label { display: block; margin-top: 16px; font-weight: 600; }\r\n");
      out.write("        input[type=\"text\"], input[type=\"number\"], input[type=\"file\"], select { width: 100%; padding: 12px 14px; border: 1px solid #d8d3ca; border-radius: 10px; margin-top: 8px; background-color: #fff; box-sizing: border-box; }\r\n");
      out.write("        .age-row { display: flex; gap: 10px; margin-top: 8px; }\r\n");
      out.write("        .age-row input[type=\"number\"] { margin-top: 0; flex: 1; }\r\n");
      out.write("        .age-row select { margin-top: 0; flex: 1; }\r\n");
      out.write("        button { width: 100%; background-color: #C98A5B; color: white; border: none; padding: 16px; border-radius: 14px; font-size: 1rem; cursor: pointer; margin-top: 24px; }\r\n");
      out.write("        button:hover { background-color: #a96e44; }\r\n");
      out.write("        .error-message { color: #d32f2f; font-size: 0.85em; margin-top: 2px; margin-bottom: 8px; display: none; }\r\n");
      out.write("        .input-error { border-color: #d32f2f !important; }\r\n");
      out.write("        .success-banner { background-color: #e8f5e9; color: #2e7d32; padding: 12px; border-radius: 6px; margin-bottom: 16px; display: none; }\r\n");
      out.write("        .error-banner { background-color: #ffebee; color: #d32f2f; padding: 12px; border-radius: 6px; margin-bottom: 16px; display: none; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <div style=\"display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px;\">\r\n");
      out.write("            <span style=\"font-size: 0.9rem; color: #555;\">Logged in as <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loggedInUser}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong></span>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" style=\"font-size: 0.9rem; color: #d32f2f;\">Logout</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <h1>Add New Pet</h1>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"successBanner\" class=\"success-banner\"></div>\r\n");
      out.write("        <div id=\"errorBanner\" class=\"error-banner\"></div>\r\n");
      out.write("\r\n");
      out.write("        <form id=\"addPetForm\" enctype=\"multipart/form-data\">\r\n");
      out.write("            <label for=\"name\">Pet Name</label>\r\n");
      out.write("            <input type=\"text\" id=\"name\" name=\"name\">\r\n");
      out.write("            <div class=\"error-message\" id=\"name-error\"></div>\r\n");
      out.write("\r\n");
      out.write("            <label>Age</label>\r\n");
      out.write("            <div class=\"age-row\">\r\n");
      out.write("                <input type=\"number\" id=\"ageValue\" name=\"ageValue\" min=\"0\" placeholder=\"e.g. 3\">\r\n");
      out.write("                <select id=\"ageUnit\" name=\"ageUnit\">\r\n");
      out.write("                    <option value=\"years\">Years</option>\r\n");
      out.write("                    <option value=\"months\">Months</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"error-message\" id=\"age-error\"></div>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"breed\">Breed</label>\r\n");
      out.write("            <input type=\"text\" id=\"breed\" name=\"breed\">\r\n");
      out.write("            <div class=\"error-message\" id=\"breed-error\"></div>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"personality\">Personality</label>\r\n");
      out.write("            <input type=\"text\" id=\"personality\" name=\"personality\">\r\n");
      out.write("            <div class=\"error-message\" id=\"personality-error\"></div>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"image\">Pet Image</label>\r\n");
      out.write("            <input type=\"file\" id=\"image\" name=\"image\" accept=\"image/*\">\r\n");
      out.write("            <div class=\"error-message\" id=\"image-error\"></div>\r\n");
      out.write("            <div id=\"imagePreview\" style=\"margin-bottom: 12px; display: none;\">\r\n");
      out.write("                <img id=\"previewImg\" src=\"\" alt=\"Preview\" style=\"max-width: 150px; max-height: 150px; border-radius: 8px; border: 1px solid #ddd;\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\">Add Pet</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        document.getElementById('image').addEventListener('change', function(e) {\r\n");
      out.write("            const file = e.target.files[0];\r\n");
      out.write("            const preview = document.getElementById('imagePreview');\r\n");
      out.write("            const previewImg = document.getElementById('previewImg');\r\n");
      out.write("            if (file) {\r\n");
      out.write("                const reader = new FileReader();\r\n");
      out.write("                reader.onload = function(ev) {\r\n");
      out.write("                    previewImg.src = ev.target.result;\r\n");
      out.write("                    preview.style.display = 'block';\r\n");
      out.write("                };\r\n");
      out.write("                reader.readAsDataURL(file);\r\n");
      out.write("            } else {\r\n");
      out.write("                preview.style.display = 'none';\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        document.getElementById('addPetForm').addEventListener('submit', function(e) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("\r\n");
      out.write("            document.querySelectorAll('.error-message').forEach(el => {\r\n");
      out.write("                el.style.display = 'none';\r\n");
      out.write("                el.textContent = '';\r\n");
      out.write("            });\r\n");
      out.write("            document.querySelectorAll('.input-error').forEach(el => {\r\n");
      out.write("                el.classList.remove('input-error');\r\n");
      out.write("            });\r\n");
      out.write("            document.getElementById('successBanner').style.display = 'none';\r\n");
      out.write("            document.getElementById('errorBanner').style.display = 'none';\r\n");
      out.write("\r\n");
      out.write("            const ageValue = parseInt(document.getElementById('ageValue').value);\r\n");
      out.write("            const ageUnit = document.getElementById('ageUnit').value;\r\n");
      out.write("\r\n");
      out.write("            if (isNaN(ageValue) || ageValue < 0) {\r\n");
      out.write("                const errorDiv = document.getElementById('age-error');\r\n");
      out.write("                errorDiv.textContent = 'Please enter a valid age.';\r\n");
      out.write("                errorDiv.style.display = 'block';\r\n");
      out.write("                document.getElementById('ageValue').classList.add('input-error');\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            const ageInMonths = ageUnit === 'years' ? ageValue * 12 : ageValue;\r\n");
      out.write("\r\n");
      out.write("            const formData = new FormData();\r\n");
      out.write("            formData.append('name', document.getElementById('name').value);\r\n");
      out.write("            formData.append('type', document.getElementById('breed').value);\r\n");
      out.write("            formData.append('age', ageInMonths);\r\n");
      out.write("\r\n");
      out.write("            const imageInput = document.getElementById('image');\r\n");
      out.write("            if (imageInput.files.length > 0) {\r\n");
      out.write("                formData.append('image', imageInput.files[0]);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/api/addPet', {\r\n");
      out.write("                method: 'POST',\r\n");
      out.write("                body: formData\r\n");
      out.write("            })\r\n");
      out.write("            .then(response => {\r\n");
      out.write("                if (!response.ok) {\r\n");
      out.write("                    return response.json().catch(() => {\r\n");
      out.write("                        throw new Error('Server error: ' + response.status);\r\n");
      out.write("                    });\r\n");
      out.write("                }\r\n");
      out.write("                return response.json();\r\n");
      out.write("            })\r\n");
      out.write("            .then(result => {\r\n");
      out.write("                if (result.status === 'success') {\r\n");
      out.write("                    window.location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/';\r\n");
      out.write("                } else if (result.status === 'error') {\r\n");
      out.write("                    const errorBanner = document.getElementById('errorBanner');\r\n");
      out.write("                    errorBanner.textContent = result.message || 'Please fix the errors below.';\r\n");
      out.write("                    errorBanner.style.display = 'block';\r\n");
      out.write("\r\n");
      out.write("                    for (const [field, message] of Object.entries(result.errors || {})) {\r\n");
      out.write("                        const errorDiv = document.getElementById(field + '-error');\r\n");
      out.write("                        const inputEl = document.getElementById(field);\r\n");
      out.write("                        if (errorDiv) {\r\n");
      out.write("                            errorDiv.textContent = message;\r\n");
      out.write("                            errorDiv.style.display = 'block';\r\n");
      out.write("                        }\r\n");
      out.write("                        if (inputEl) {\r\n");
      out.write("                            inputEl.classList.add('input-error');\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("            .catch(err => {\r\n");
      out.write("                const errorBanner = document.getElementById('errorBanner');\r\n");
      out.write("                errorBanner.textContent = 'An unexpected error occurred. Please try again.';\r\n");
      out.write("                errorBanner.style.display = 'block';\r\n");
      out.write("                console.error(err);\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
