/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-04-01 01:57:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>Paws - Pet Adoption</title>\r\n");
      out.write("\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/paws.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!-- NAVBAR -->\r\n");
      out.write("  <nav class=\"navbar navbar-expand-lg\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <a class=\"navbar-brand fw-bold fs-4\" href=\"#\">PAWS</a>\r\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("        <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link px-3\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">Home</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item dropdown\">\r\n");
      out.write("            <a class=\"nav-link px-3 dropdown-toggle\" href=\"#\" data-bs-toggle=\"dropdown\">Adopt</a>\r\n");
      out.write("            <ul class=\"dropdown-menu\">\r\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/#pets\">Browse Pets</a></li>\r\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/adoption\">Adoption Form</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link px-3\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/contact\">Contact</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item dropdown\">\r\n");
      out.write("            <a class=\"nav-link px-3 dropdown-toggle\" href=\"#\" data-bs-toggle=\"dropdown\">Account</a>\r\n");
      out.write("            <ul class=\"dropdown-menu dropdown-menu-end\">\r\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\">Login</a></li>\r\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/userregister\">Register</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- HERO SECTION -->\r\n");
      out.write("  <section id=\"home\" style=\"\r\n");
      out.write("    background-image: url('https://i.pinimg.com/1200x/d1/d1/81/d1d18156545ed373db49a08fa9896488.jpg');\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    background-position: bottom;\r\n");
      out.write("    padding: 100px 0;\r\n");
      out.write("    text-align: center;\">\r\n");
      out.write("\r\n");
      out.write("    <div style=\"background-color: rgba(0,0,0,0.4); padding: 40px 20px;\">\r\n");
      out.write("      <h1 style=\"color: white;\">Paws Pet Adoption Center</h1>\r\n");
      out.write("      <p style=\"color: #f0e6dc; max-width: 600px; margin: 0 auto;\">\r\n");
      out.write("        Welcome to <b>Paws</b>, a non-profit center dedicated to rescuing and rehoming abandoned animals.\r\n");
      out.write("        <br>Each pet has a unique personality and story.\r\n");
      out.write("        <br><br>Click on any pet to learn more about their age, breed, and temperament.\r\n");
      out.write("      </p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- PETS SECTION -->\r\n");
      out.write("  <section class=\"py-5\" id=\"pets\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <h2 class=\"text-center mb-5\">Pets Available for Adoption</h2>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"row g-4 justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Max -->\r\n");
      out.write("        <div class=\"col-12 col-md-6 col-lg-4 d-flex justify-content-center\">\r\n");
      out.write("          <div class=\"card h-100 text-center border-0 rounded-3 overflow-hidden\" style=\"max-width: 300px; width: 100%;\">\r\n");
      out.write("            <a href=\"max.html\">\r\n");
      out.write("              <img src=\"https://i.pinimg.com/736x/8d/9e/79/8d9e79283188acabd27436f8ca640d30.jpg\" class=\"card-img-top\" style=\"width:100%; height:300px; object-fit:cover; object-position:center top; border-bottom: 3px solid #e8d5c2;\" alt=\"Max the Labrador\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"card-body d-flex flex-column p-3\">\r\n");
      out.write("              <h5 class=\"card-title fw-semibold mb-1\">Max</h5>\r\n");
      out.write("              <ul class=\"list-unstyled mb-2 small\">\r\n");
      out.write("                <li><b>Age:</b> 2 Years</li>\r\n");
      out.write("                <li><b>Breed:</b> Labrador</li>\r\n");
      out.write("                <li><b>Personality:</b> Playful, friendly, active</li>\r\n");
      out.write("              </ul>\r\n");
      out.write("              <a href=\"max.html\" class=\"btn btn-adopt mt-auto\">View Details</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Moon -->\r\n");
      out.write("        <div class=\"col-12 col-md-6 col-lg-4 d-flex justify-content-center\">\r\n");
      out.write("          <div class=\"card h-100 text-center border-0 rounded-3 overflow-hidden\" style=\"max-width: 300px; width: 100%;\">\r\n");
      out.write("            <a href=\"moon.html\">\r\n");
      out.write("              <img src=\"https://i.pinimg.com/1200x/c4/10/3e/c4103e72b3052ce73f2ce02c5793131f.jpg\" class=\"card-img-top\" style=\"width:100%; height:300px; object-fit:cover; object-position:center top; border-bottom: 3px solid #e8d5c2;\" alt=\"Moon the Pug\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"card-body d-flex flex-column p-3\">\r\n");
      out.write("              <h5 class=\"card-title fw-semibold mb-1\">Moon</h5>\r\n");
      out.write("              <ul class=\"list-unstyled mb-2 small\">\r\n");
      out.write("                <li><b>Age:</b> 5 Years</li>\r\n");
      out.write("                <li><b>Breed:</b> Pug</li>\r\n");
      out.write("                <li><b>Personality:</b> Friendly, shy, gentle</li>\r\n");
      out.write("              </ul>\r\n");
      out.write("              <a href=\"moon.html\" class=\"btn btn-adopt mt-auto\">View Details</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Tommy -->\r\n");
      out.write("        <div class=\"col-12 col-md-6 col-lg-4 d-flex justify-content-center\">\r\n");
      out.write("          <div class=\"card h-100 text-center border-0 rounded-3 overflow-hidden\" style=\"max-width: 300px; width: 100%;\">\r\n");
      out.write("            <a href=\"tommy.html\">\r\n");
      out.write("              <img src=\"https://i.pinimg.com/736x/29/f7/00/29f7007bdf91df2385e0394b60ed0568.jpg\" class=\"card-img-top\" style=\"width:100%; height:300px; object-fit:cover; object-position:center top; border-bottom: 3px solid #e8d5c2;\" alt=\"Tommy the dog\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"card-body d-flex flex-column p-3\">\r\n");
      out.write("              <h5 class=\"card-title fw-semibold mb-1\">Tommy</h5>\r\n");
      out.write("              <ul class=\"list-unstyled mb-2 small\">\r\n");
      out.write("                <li><b>Age:</b> 4 Years</li>\r\n");
      out.write("                <li><b>Breed:</b> Mixed</li>\r\n");
      out.write("                <li><b>Personality:</b> Friendly, loving</li>\r\n");
      out.write("              </ul>\r\n");
      out.write("              <a href=\"tommy.html\" class=\"btn btn-adopt mt-auto\">View Details</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Luna -->\r\n");
      out.write("        <div class=\"col-12 col-md-6 col-lg-4 d-flex justify-content-center\">\r\n");
      out.write("          <div class=\"card h-100 text-center border-0 rounded-3 overflow-hidden\" style=\"max-width: 300px; width: 100%;\">\r\n");
      out.write("            <a href=\"luna.html\">\r\n");
      out.write("              <img src=\"https://i.pinimg.com/736x/3d/08/f3/3d08f312d3572139716883cb4c4ba94f.jpg\" class=\"card-img-top\" style=\"width:100%; height:300px; object-fit:cover; object-position:center top; border-bottom: 3px solid #e8d5c2;\" alt=\"Luna the cat\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"card-body d-flex flex-column p-3\">\r\n");
      out.write("              <h5 class=\"card-title fw-semibold mb-1\">Luna</h5>\r\n");
      out.write("              <ul class=\"list-unstyled mb-2 small\">\r\n");
      out.write("                <li><b>Age:</b> 1 Year</li>\r\n");
      out.write("                <li><b>Breed:</b> Domestic Shorthair</li>\r\n");
      out.write("                <li><b>Personality:</b> Calm, affectionate</li>\r\n");
      out.write("              </ul>\r\n");
      out.write("              <a href=\"luna.html\" class=\"btn btn-adopt mt-auto\">View Details</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Bella -->\r\n");
      out.write("        <div class=\"col-12 col-md-6 col-lg-4 d-flex justify-content-center\">\r\n");
      out.write("          <div class=\"card h-100 text-center border-0 rounded-3 overflow-hidden\" style=\"max-width: 300px; width: 100%;\">\r\n");
      out.write("            <a href=\"bella.html\">\r\n");
      out.write("              <img src=\"https://i.pinimg.com/736x/49/4e/93/494e93198c2a1959772b05777fb2ae8f.jpg\" class=\"card-img-top\" style=\"width:100%; height:300px; object-fit:cover; object-position:center top; border-bottom: 3px solid #e8d5c2;\" alt=\"Bella the cat\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"card-body d-flex flex-column p-3\">\r\n");
      out.write("              <h5 class=\"card-title fw-semibold mb-1\">Bella</h5>\r\n");
      out.write("              <ul class=\"list-unstyled mb-2 small\">\r\n");
      out.write("                <li><b>Age:</b> 3 Years</li>\r\n");
      out.write("                <li><b>Breed:</b> Domestic Shorthair</li>\r\n");
      out.write("                <li><b>Personality:</b> Friendly, playful</li>\r\n");
      out.write("              </ul>\r\n");
      out.write("              <a href=\"bella.html\" class=\"btn btn-adopt mt-auto\">View Details</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Cookie -->\r\n");
      out.write("        <div class=\"col-12 col-md-6 col-lg-4 d-flex justify-content-center\">\r\n");
      out.write("          <div class=\"card h-100 text-center border-0 rounded-3 overflow-hidden\" style=\"max-width: 300px; width: 100%;\">\r\n");
      out.write("            <a href=\"cookie.html\">\r\n");
      out.write("              <img src=\"https://i.pinimg.com/1200x/b4/e1/3d/b4e13d421892a0e0023a7dde6dab3f31.jpg\" class=\"card-img-top\" style=\"width:100%; height:300px; object-fit:cover; object-position:center top; border-bottom: 3px solid #e8d5c2;\" alt=\"Cookie the cat\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"card-body d-flex flex-column p-3\">\r\n");
      out.write("              <h5 class=\"card-title fw-semibold mb-1\">Cookie</h5>\r\n");
      out.write("              <ul class=\"list-unstyled mb-2 small\">\r\n");
      out.write("                <li><b>Age:</b> 1 Year</li>\r\n");
      out.write("                <li><b>Breed:</b> Domestic Shorthair</li>\r\n");
      out.write("                <li><b>Personality:</b> Playful, shy</li>\r\n");
      out.write("              </ul>\r\n");
      out.write("              <a href=\"cookie.html\" class=\"btn btn-adopt mt-auto\">View Details</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- INFO SECTION -->\r\n");
      out.write("  <section class=\"py-5\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"bg-light rounded-3 p-4 p-md-5\">\r\n");
      out.write("        <div class=\"row g-4\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-12 col-md-4\">\r\n");
      out.write("            <h2>Our Services</h2>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li>Pet rescue and rehabilitation</li>\r\n");
      out.write("              <li>Vaccination and health checkups</li>\r\n");
      out.write("              <li>Adoption counseling</li>\r\n");
      out.write("              <li>Basic training guidance</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-12 col-md-4\">\r\n");
      out.write("            <h2>Adoption Process</h2>\r\n");
      out.write("            <p>\r\n");
      out.write("              Interested adopters can visit our center, meet the pets, and complete a short\r\n");
      out.write("              adoption form. Our team ensures a good match between pet and owner.\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-12 col-md-4\">\r\n");
      out.write("            <h2>Why Adopt From Paws?</h2>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li>Fully vaccinated pets</li>\r\n");
      out.write("              <li>Medical history provided</li>\r\n");
      out.write("              <li>Safe and caring environment</li>\r\n");
      out.write("              <li>Post-adoption support</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- FOOTER -->\r\n");
      out.write("  <footer>\r\n");
      out.write("    <p><b>Opening Hours:</b> Sunday - Friday | 10:00 AM - 5:00 PM</p>\r\n");
      out.write("    <p>Â© 2026 Paws Pet Adoption. All rights reserved.</p>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap JS -->\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
