package com.example.model;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;

/**
 * Employee Model — represents an employee in the Controller and View layers.
 *
 * This class has validation annotations that check user input:
 * - @NotBlank: the field cannot be empty
 * - @Email: must be a valid email format (like "john@example.com")
 * - @Pattern: must match a specific pattern (here, exactly 10 digits)
 *
 * These validations are triggered when the Controller uses @Valid on a request.
 * If any validation fails, Spring collects the errors so we can show them to the user.
 */
public class Employee {

    private Long id;  // Auto-generated by the database

    @NotBlank(message = "Name is required")
    private String name;

    @NotBlank(message = "Email is required")
    @Email(message = "Email must be a valid email address")
    private String email;

    @NotBlank(message = "Contact number is required")
    @Pattern(regexp = "^\\d{10}$", message = "Contact number must be exactly 10 digits")
    private String contactNumber;

    @NotBlank(message = "Position is required")
    private String position;

    // No-argument constructor — required by Jackson to convert JSON into this object
    public Employee() {
    }

    // Constructor with all fields (except id, which is auto-generated)
    public Employee(String name, String email, String contactNumber, String position) {
        this.name = name;
        this.email = email;
        this.contactNumber = contactNumber;
        this.position = position;
    }

    // Getters and Setters — used by Spring and Jackson to read/write field values

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getContactNumber() {
        return contactNumber;
    }

    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }
}
