package com.example.model;

import jakarta.validation.constraints.NotBlank;

/**
 * Pet Model — represents a pet in the system.
 */
public class Pet {

    private Long id;  // Auto-generated by the database

    @NotBlank(message = "Name is required")
    private String name;

    @NotBlank(message = "Type is required")
    private String type;

    private int age;

    private String personality;

    private byte[] image;  // Image data stored as byte array

    // No-argument constructor — required by Jackson
    public Pet() {
    }

    // Constructor with all fields (except id)
    public Pet(String name, String type, int age, String personality, byte[] image) {
        this.name = name;
        this.type = type;
        this.age = age;
        this.personality = personality;
        this.image = image;
    }

    // Getters and Setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getPersonality() {
        return personality;
    }

    public void setPersonality(String personality) {
        this.personality = personality;
    }

    public byte[] getImage() {
        return image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }
}