package com.example.model;

import jakarta.validation.constraints.NotBlank;

/**
 * Pet Model — represents a pet in the system.
 */
public class Pet {

    private Long id;  // Auto-generated by the database

    @NotBlank(message = "Name is required")
    private String name;

    @NotBlank(message = "Type is required")
    private String type;

    private int age;

    private String imagePath;  // Path to the uploaded image

    // No-argument constructor — required by Jackson
    public Pet() {
    }

    // Constructor with all fields (except id)
    public Pet(String name, String type, int age, String imagePath) {
        this.name = name;
        this.type = type;
        this.age = age;
        this.imagePath = imagePath;
    }

    // Getters and Setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getImagePath() {
        return imagePath;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }
}